# Generated by Django 5.1.5 on 2025-07-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='license_expiry_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='preferred_payment_method',
            field=models.CharField(default='Mpesa', max_length=20),
        ),
    ]
