# Generated by Django 5.1.5 on 2025-07-28 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_driver_license_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='preferred_payment_method',
            field=models.CharField(default='wallet', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('driver', 'Driver'), ('passenger', 'Passenger')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='driver',
            table='driver_profiles',
        ),
        migrations.AlterModelTable(
            name='passenger',
            table='passenger_profiles',
        ),
    ]
