# Generated by Django 5.1.5 on 2025-11-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures//default-profile.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
