# Generated by Django 5.1.5 on 2025-12-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle_picture',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_pictures/'),
        ),
    ]
