# Generated by Django 5.1.5 on 2026-01-28 20:29

import django.core.validators
from django.db import migrations, models


def delete_null_phones(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    # Delete users with NULL phone numbers (the duplicates identified in 0007)
    User.objects.filter(phone_number__isnull=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_cleanup_phone_duplicates'),
    ]

    operations = [
        migrations.RunPython(delete_null_phones),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default-profile.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
