# Generated by Django 5.1.5 on 2026-03-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
