# Generated by Django 5.1.5 on 2026-01-12 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transaction_completed_at_transaction_result_code_and_more'),
        ('rides', '0003_alter_ride_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='rides.booking'),
        ),
    ]
