# Generated by Django 5.1.5 on 2026-03-03 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_backfill_mpesa_reference'),
        ('rides', '0009_alter_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='rides.ride'),
        ),
    ]
