# Generated by Django 5.1.5 on 2026-03-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_transaction_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
