# Generated by Django 5.1.5 on 2026-03-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup', 'Top-up'), ('booking', 'Booking Payment'), ('ride_fee', 'Ride Fee'), ('withdrawal', 'Withdrawal')], default='topup', max_length=20),
        ),
    ]
