# Generated by Django 5.1.5 on 2025-08-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='description',
            new_name='additional_info',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='total_seats',
        ),
        migrations.AlterField(
            model_name='ride',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
    ]
