# Generated by Django 5.1.5 on 2025-08-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_rename_description_ride_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='available_seats',
            field=models.IntegerField(default=1),
        ),
    ]
