# Generated by Django 5.1.5 on 2026-01-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_ride_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='ride_images/'),
        ),
    ]
