# Generated by Django 5.1.5 on 2026-01-15 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_ride_vehicle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='vehicle_image',
        ),
        migrations.CreateModel(
            name='RideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ride_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rides.ride')),
            ],
        ),
    ]
