# Generated by Django 5.1.5 on 2026-01-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_remove_ride_vehicle_image_rideimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_location',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('fully_booked', 'Fully Booked')], db_index=True, default='available', max_length=20),
        ),
    ]
