# Generated by Django 5.1.5 on 2026-03-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_booking_seats_deducted_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('fully_booked', 'Fully Booked'), ('pending_payment', 'Pending Payment')], db_index=True, default='available', max_length=20),
        ),
    ]
